(setq modus-vivendi-palette-overrides
      '(;; Core Background and Foreground
        (bg-main "#1a1a1a")        ;; Editor background (Night)
        (bg-dim "#080808")         ;; Alternate/Dim background (bg-alt from source)
        (bg-active "#262626")      ;; Editor background (Storm) / Active elements
        (bg-inactive "#161616")    ;; Inactive panels
        (fg-main "#aaaaaa")        ;; Editor foreground
        (fg-dim "#666666")         ;; Comments (dark-blue)
        (fg-dim-alt "#909090")
        ;; --- Semantic Colors (From Provided List) ---
        (red                            "#f7768e")
        (red-warmer                     "#e6785e")
        (red-cooler                     "#e07888")
        (red-faint                      "#e8b8ab")
        (red-intense                    "#e65555")
        (green                          "#9ece6a")
        (green-warmer                   "#5ebc89")
        (green-cooler                   "#73daca")
        (green-faint                    "#7cc2a6")
        (green-intense                  "#3cc9a4")
        (yellow                         "#e0af68")
        (yellow-warmer                  "#f0b060")
        (yellow-cooler                  "#c0cf6a")
        (yellow-faint                   "#e0d38c")
        (yellow-intense                 "#f0c060")
        (blue                           "#7aa2f7")
        (blue-warmer                    "#9ab0f7")
        (blue-cooler                    "#7dcfff")
        (blue-faint                     "#c0d8eb")
        (blue-intense                   "#5a9aff")
        (magenta                        "#bb9af7")
        (magenta-warmer                 "#f7a8d0")
        (magenta-cooler                 "#9d7cd8")
        (magenta-faint                  "#d8c0e8")
        (magenta-intense                "#c07af7")
        (cyan                           "#b4f9f8")
        (cyan-warmer                    "#b3ffd9")
        (cyan-cooler                    "#7de5ff")
        (cyan-faint                     "#6ac4c3")
        (cyan-intense                   "#2ac3de")
        (orange                         "#ff9e64")
        (rust                           "#c07a5a")
        (gold                           "#c0a05b")
        (olive                          "#a3bfa3")
        (slate                          "#8099a0")
        (indigo                         "#857ec5")
        (maroon                         "#b569c0")
        (pink                           "#d8c0e8")
        (bg-red-intense                 "#9d1f1f")

        (rainbow-0 fg-main)
        (rainbow-1 blue)
        (rainbow-2 orange)
        (rainbow-3 green-cooler)
        (rainbow-4 cyan-cooler)
        (rainbow-5 yellow)
        (rainbow-6 cyan-intense)
        (rainbow-7 magenta-warmer)
        (rainbow-8 blue-warmer)

        (bg-paren-match magenta-intense)
        (fg-paren-match bg-main)

        (fg-prose-block-delimiter fg-dim)

        (fringe unspecified)
        (bg-line-number-inactive unspecified)
        (border-mode-line-active unspecified)
        (border-mode-line-inactive unspecified)

        (string green)
        (variable fg-main)
        (variable-use fg-main)
        (type fg-main)
        (name blue)
        (fname blue)
        (fname-call blue)
        (builtin red)
        (docstring fg-dim-alt)
        (keyword magenta)
        (property blue-cooler)

        (fg-prompt blue)
        (fg-prose-code blue)
        ;; headers -----------------------
        (fg-heading-1 "#7AA2F7")
        (fg-heading-2 "#CF92FB")
        (fg-heading-3 "#FE9CC1")
        (fg-heading-4 "#FFB9A0")
        (fg-heading-5 "#FFD56F")
        (fg-heading-6 "#BEFF8D")
        (fg-heading-7 "#DEFFF7")
        (fg-heading-8 "#FFFFFF")))


